server.forward-headers-strategy=framework
# app
app.allow.origins=${APP_ALLOW_ORIGINS}
# redis
spring.data.redis.url=${REDIS_URL}
# Kafka broker address
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
# postgresql
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Chroma Vector Store
spring.ai.vectorstore.chroma.client.host=${CHROMA_HOST:http://chromadb}
spring.ai.vectorstore.chroma.client.port=${CHROMA_PORT:8000}
spring.ai.vectorstore.chroma.client.username=${CHROMA_USERNAME:admin}
spring.ai.vectorstore.chroma.client.password=${CHROMA_PASSWORD:}
# embedding
spring.ai.google.genai.embedding.api-key=${GOOGLE_AI_EMBEDDING_API_KEY:}
# dbdiagram configuration
dbdiagram.base-url=https://api.dbdiagram.io/v1
dbdiagram.token=${DBDIAGRAM_TOKEN}
# bitbucket cloud configuration
bitbucket.base-url=https://api.bitbucket.org/2.0
bitbucket.username=${BITBUCKET_USERNAME}
bitbucket.token=${BITBUCKET_TOKEN}
## S3 Storage
s3-client.access-key-id=${S3_ACCESS_KEY_ID}
s3-client.secret-access-key=${S3_SECRET_ACCESS_KEY}
s3-client.region=us-east-1
s3-client.endpoint=http://minio.ezisolutions.vn:9099
s3-client.public-url=https://minio.ezisolutions.vn/storage
s3-client.bucket=storage
